export * from "./auth";
export * from "./dashboard";
export * from "./designacao/lista";
export * from "./designacao";
export * from "./hello";
export * from "./consultar";
export * from "./peticao";
export * from "./peticao/formulario";
export * from "./peticao/upload";
