name: Serverless Framework CloudFront Deployment

on:
  push:
    branches: [ "dev", "hmg", "main" ]
  pull_request:
    branches: [ "dev", "hmg", "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Set environment variables based on branch
      run: |
        if [[ ${{ github.ref }} == 'refs/heads/dev' ]]; then
          echo "NODE_ENV=dev" >> $GITHUB_ENV
        elif [[ ${{ github.ref }} == 'refs/heads/hmg' ]]; then
          echo "NODE_ENV=hmg" >> $GITHUB_ENV
        elif [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
          echo "NODE_ENV=prod" >> $GITHUB_ENV
        fi
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - name: Deploy
      run: npm run deploy
      env:
        NODE_ENV: ${{ env.NODE_ENV }}
